name: Build GDX

on:
  push:
    branches:
      - yellowfin
      - albacore
      - bluefin-tuna
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: ${{ github.ref_name }}-gdx
      flavor: gdx
      major-version: ${{ github.ref_name == 'albacore' && '10' || github.ref_name == 'yellowfin' && '10' || github.ref_name == 'bluefin-tuna' && '42' || github.ref_name == 'main' && 'stream10' || github.ref_name }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
