name: Build Bluefin LTS

on:
  pull_request:
    branches:
      - main
      - F42
      - a10
      - a10s
      - a10-server
  push:
    branches:
      - main
      - F42
      - a10
      - a10s
      - a10-server
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: bluefin
      major-version: ${{ github.ref_name == 'a10' && '10' || github.ref_name == 'a10s' && '10s' || github.ref_name == 'F42' && '42' || github.ref_name == 'main' && 'stream10' || github.ref_name }}
      default-tag: ${{ github.ref_name == 'main' && 'lts' || github.ref_name }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
      platforms: ${{ github.ref_name == 'a10-server' && 'amd64,arm64,amd64/v2' || github.ref_name == 'a10' && 'amd64,arm64,amd64/v2' || github.ref_name == 'a10s' && 'amd64,arm64,amd64/v2' ||'amd64' }}
